### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by samir324** [samir324/projet_profisonnel_1#1]
- [x] BEM

- [ ] NodeJS

- [x] Node_scss

- [x] Cascading

**Comment by youssefbm** [comment]
Ajouter la spécificité et le cascading dans la documentation

**Comment by samir324** [comment]
[image: image.png]
voila, la modification est faite et merci.

Le lun. 24 févr. 2020 à 14:07, YoussefOuadid <notifications@github.com> a
écrit :

**Comment by youssefbm** [comment]
Jeter un coup d'oeil sur cette video: https://www.youtube.com/watch?v=yva2bj-lVRA
